### ISSUE TITLE
Broken / incorrect links following HL7 release of R4

### ISSUE THREAD

**Issue by TimCoates** [nhsconnect/NHS-Booking-API#1]
As a result of STU3 resources being moved on the HL7 server, links from e.g. https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-HealthcareService-1 to the underlying HL7 resource profile (Shown as Constrained URL) are now going to R4 resources. This can and will cause confusion amongst those trying to implement the specifications. Ideally HL7 would version their resources, but failing that either some very clear labelling (I doubt it could be made obvious enough to prevent confusion) or uplifting all links to HL7 STU3 links is perhaps required?

**Comment by bushra** [comment]
I've checked the link in the Constrained URL and it directs to the STU3 resource. This change was anticipated following the publication of the STU3 FHIR spec, so the profile rendering code applies the STU3 URL at publication.
