### ISSUE TITLE
Incorrect cardinalities on resuorce overview pages

### ISSUE THREAD

**Issue by TimCoates** [nhsconnect/NHS-Booking-API#2]
The *Key FHIR Elements* section of pages describing resources has cardinality which is out of step with the profiles. For example on: https://nhsconnect.github.io/FHIR-A2SI-APPOINTMENTS-API/api_uec_appointments_healthcare_service.html HealthcareService.providedBy is shown as 1..1 whereas in the profile it is 0..1. The profiles appear to be correct, so maybe change the pages to reflect the profile values. NB: Should Key elements only be those which are used to link to other resources?

**Comment by bushra** [comment]
I've checked and you have applied this fix in 1.0.4 so will close https://nhsconnect.github.io/NHS-Scheduling-API/healthcare_service.html
