### ISSUE TITLE
Diagram shows Dos ID instead of 

### ISSUE THREAD

**Issue by TimCoates** [nhsconnect/NHS-Booking-API#3]
The diagram at: https://nhsconnect.github.io/FHIR-A2SI-APPOINTMENTS-API/explore.html#urgent--emergency-care-appointments-apis shows DOS Id being passed as a search parameter. This should be HealthcareService.id as correctly shown on https://nhsconnect.github.io/FHIR-A2SI-APPOINTMENTS-API/search_free_slots.html#search-parameters

**Comment by bushra** [comment]
I've checked and you have applied this fix in 1.0.4 so will close https://nhsconnect.github.io/NHS-Scheduling-API/resources_overview.html
