### ISSUE TITLE
Broken JSON

### ISSUE THREAD

**Issue by TimCoates** [nhsconnect/NHS-Booking-API#4]
The example Appointment resource on this page
https://nhsconnect.github.io/FHIR-A2SI-APPOINTMENTS-API/book_an_appointment.html  has a few errors:
The contained [] is repeated, whereas there should be one contained [] with two objects in it.
There's a missing comma after "required" 5 lines from the bottom.
There's an extra comma after "use": "home" (about halfway down.

**Comment by bushra** [comment]
i can see that this example has been removed from the 1.0.4. spec but I've had a go at fixing what was in 1.0.3. If you are happy with this let me know. 
[Appointment-example.txt](https://github.com/nhsconnect/NHS-Scheduling-API/files/3285495/Appointment-example.txt)

**Comment by bushra** [comment]
I can see that the examples for the Appointment resource have been corrected at https://nhsconnect.github.io/NHS-Scheduling-API/appointment.html so will close this.
