### ISSUE TITLE
PractitionerRole.code example is unhelpful.

### ISSUE THREAD

**Issue by TimCoates** [nhsconnect/NHS-Booking-API#5]
The example provided on https://nhsconnect.github.io/FHIR-A2SI-APPOINTMENTS-API/api_uec_appointments_entity_practitioner_role.html#1-key-fhir-elements suggests a value which is different from the required value as https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-PractitionerRole-1   Suggest example should show the 'required' value instead.

**Comment by bushra** [comment]
I can see this has changed in 1.0.4 so will close.
