### ISSUE TITLE
Branch marked as Default is empty

### ISSUE THREAD

**Issue by TimCoates** [nhsconnect/NHS-Booking-API#7]
The master branch is marked as default (and therefore shows when you browse to the Repo), but this only contains a readme.md file. It might be helpful merging the latest / current branch into master.

**Comment by NaminderSoorma** [comment]
We don't use master branch.... guidance is that we use develop so best to make that one default.

**Comment by bushra** [comment]
The repository has been updated to use 'develop' and 'master' only. Subsequent changes to the spec can be made in develop for review, prior to merging into 'master' for publication.
